# Generated by Django 5.2.5 on 2025-08-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscribed_at',
            new_name='created_at',
        ),
    ]
